### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by lkurylo** [MKruschke/ts-meets-a-multi-packages-application#21]
I can't build this solution
![image](https://user-images.githubusercontent.com/744244/148742958-239ac06d-e1c2-465f-b3c5-6264cbcc6fed.png)
Shouldn't this be configured with local npm packages?

Doing it through npm registry, every change in referenced packages will require to update the references in registry and in packages. Am I right? I'm trying to grasp the concept of npm workspaces and ts project references so maybe I'm missing someting?

**Comment by lkurylo** [comment]
I got it to work. 
I installed the dependencies by _npm i_ in each of the packages, but I should do it in main project only.

**Comment by MKruschke** [comment]
Hi @lkurylo,
usually you need to do a `npm install` on the root level. After that the workspace should be setup correctly and all local packages should be resolved correctly. Does you use npm with a version >= 7 ? 

```
npm install
npm run ts:build
```

BR Mirko
